# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_dateForm.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!

# Generated by pyuic5 -- see MainWindow.py for what that means and why this
# file is never hand-edited. Behavior lives in _date.py.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(547, 327)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        # QTimeEdit is a spinbox-like widget specialized for entering a time
        # of day (hours/minutes/seconds), with up/down arrows to adjust each
        # part. setCalendarPopup(True) is really meant for date widgets (see
        # dateStart/dateEnd below); it has no visible effect on a plain
        # QTimeEdit like this one, but pyuic5 still emits it because it's
        # simply part of every *Edit widget's common property set.
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(50, 100, 141, 41))
        self.timeEdit.setCalendarPopup(True)
        self.timeEdit.setObjectName("timeEdit")
        # QDateTimeEdit combines a date AND a time into a single editable
        # field. setCalendarPopup(True) adds a small "open calendar" button
        # that pops up a visual month calendar to pick the date part from,
        # instead of typing digits.
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(200, 100, 231, 41))
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.btnCalculate = QtWidgets.QPushButton(self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(50, 170, 131, 41))
        self.btnCalculate.setObjectName("btnCalculate")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 30, 351, 31))
        self.widget.setObjectName("widget")
        # A QHBoxLayout (see layouts.py) laying the two date pickers below
        # out side by side with a gap between them.
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        # QDateEdit is like QTimeEdit but for calendar dates (day/month/year)
        # instead of a time of day.
        self.dateStart = QtWidgets.QDateEdit(self.widget)
        # QSizePolicy tells the layout how a widget should behave when there
        # is extra or too little space to distribute: here, "Minimum"
        # horizontally means the widget should be given only as much
        # horizontal room as it needs (not stretched to fill leftover
        # space), and "Preferred" vertically is the normal default. This
        # block of sizePolicy code is boilerplate pyuic5 generates whenever
        # a widget's size policy was customized in Qt Designer.
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateStart.sizePolicy().hasHeightForWidth())
        self.dateStart.setSizePolicy(sizePolicy)
        self.dateStart.setCalendarPopup(True)
        # setDate() sets the widget's initial value. QtCore.QDate(year,
        # month, day) constructs a specific calendar date object -- here,
        # January 1st, 2001.
        self.dateStart.setDate(QtCore.QDate(2001, 1, 1))
        self.dateStart.setObjectName("dateStart")
        self.horizontalLayout.addWidget(self.dateStart)
        # QSpacerItem is an invisible "spring" you can insert into a layout
        # to push widgets apart. This one is a fixed 70px-wide gap (Fixed
        # horizontally) between the two date pickers, instead of relying on
        # the layout's own default spacing.
        spacerItem = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.dateEnd = QtWidgets.QDateEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEnd.sizePolicy().hasHeightForWidth())
        self.dateEnd.setSizePolicy(sizePolicy)
        self.dateEnd.setObjectName("dateEnd")
        self.horizontalLayout.addWidget(self.dateEnd)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 547, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnCalculate.setText(_translate("MainWindow", "PushButton"))
