# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_radiobuttonForm.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!

# Generated by pyuic5 -- see MainWindow.py for what that means and why this
# file is never hand-edited. Behavior lives in _radiobutton.py.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(561, 435)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_country = QtWidgets.QLabel(self.centralwidget)
        self.lbl_country.setGeometry(QtCore.QRect(20, 250, 191, 91))
        self.lbl_country.setText("")
        self.lbl_country.setObjectName("lblUlke")
        self.lbl_education = QtWidgets.QLabel(self.centralwidget)
        self.lbl_education.setGeometry(QtCore.QRect(260, 260, 171, 81))
        self.lbl_education.setText("")
        self.lbl_education.setObjectName("lblEgitim")
        self.btn_country = QtWidgets.QPushButton(self.centralwidget)
        self.btn_country.setGeometry(QtCore.QRect(50, 190, 141, 41))
        self.btn_country.setObjectName("btnUlke")
        self.btn_education = QtWidgets.QPushButton(self.centralwidget)
        self.btn_education.setGeometry(QtCore.QRect(210, 190, 141, 41))
        self.btn_education.setObjectName("btnEgitim")
        # QGroupBox (see _checkboxForm.py) grouping the "country" radio
        # buttons visually. Grouping radio buttons like this also matters
        # functionally: PyQt5 automatically treats radio buttons that share
        # the same parent as one mutually-exclusive set, so selecting one
        # here automatically unselects the others in the SAME group box --
        # while leaving the separate "education" group's selection
        # untouched, since that's a different parent/group entirely.
        self.group_box_country = QtWidgets.QGroupBox(self.centralwidget)
        self.group_box_country.setGeometry(QtCore.QRect(20, 20, 181, 151))
        self.group_box_country.setObjectName("groupBoxUlke")
        self.gridLayoutWidget = QtWidgets.QWidget(self.group_box_country)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 141, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        # QGridLayout (see layouts.py) arranges widgets in a table of rows
        # and columns. addWidget(widget, row, column, rowSpan, colSpan)
        # places a widget at that cell -- here every radio button spans
        # just 1 row and 1 column, all stacked in column 0 across different
        # rows, so visually it still looks like a simple vertical list.
        self.grid_layout_country = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.grid_layout_country.setContentsMargins(0, 0, 0, 0)
        self.grid_layout_country.setObjectName("gridLayoutUlke")
        # QRadioButton is a round selectable button, normally used in
        # groups where only ONE option can be chosen at a time (unlike
        # QCheckBox, where any number can be checked independently). Note
        # these four are added to the grid layout in a different order
        # (Germany at row 2, Turkey at row 0, Azerbaijan at row 1, Greece at
        # row 3) than they're created in code -- the row/column numbers
        # passed to addWidget() control the visual order, not the order
        # these lines run in.
        self.radio_germany = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_germany.setObjectName("radioAlmanya")
        self.grid_layout_country.addWidget(self.radio_germany, 2, 0, 1, 1)
        self.radio_turkey = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_turkey.setObjectName("radioTurkiye")
        self.grid_layout_country.addWidget(self.radio_turkey, 0, 0, 1, 1)
        self.radio_azerbaijan = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_azerbaijan.setObjectName("radioAzerbaycan")
        self.grid_layout_country.addWidget(self.radio_azerbaijan, 1, 0, 1, 1)
        self.radio_greece = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radio_greece.setObjectName("radioYunanistan")
        self.grid_layout_country.addWidget(self.radio_greece, 3, 0, 1, 1)
        # A second, independent radio-button group for education level --
        # its own QGroupBox means its own separate mutually-exclusive set,
        # unrelated to the country group above.
        self.group_box_education = QtWidgets.QGroupBox(self.centralwidget)
        self.group_box_education.setGeometry(QtCore.QRect(240, 20, 191, 151))
        self.group_box_education.setObjectName("groupBoxEgitim")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.group_box_education)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 20, 141, 121))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.grid_layout_education = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.grid_layout_education.setContentsMargins(0, 0, 0, 0)
        self.grid_layout_education.setObjectName("gridLayoutEgitim")
        self.radio_university = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radio_university.setObjectName("radioUniversite")
        self.grid_layout_education.addWidget(self.radio_university, 2, 0, 1, 1)
        self.radio_elementary = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radio_elementary.setObjectName("radioilkokul")
        self.grid_layout_education.addWidget(self.radio_elementary, 0, 0, 1, 1)
        self.radio_high_school = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radio_high_school.setObjectName("radioLise")
        self.grid_layout_education.addWidget(self.radio_high_school, 1, 0, 1, 1)
        self.radio_masters = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radio_masters.setObjectName("radioYuksekLisans")
        self.grid_layout_education.addWidget(self.radio_masters, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 561, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_country.setText(_translate("MainWindow", "Select Country"))
        self.btn_education.setText(_translate("MainWindow", "Select Education"))
        self.group_box_country.setTitle(_translate("MainWindow", "Countries"))
        self.radio_germany.setText(_translate("MainWindow", "Germany"))
        self.radio_turkey.setText(_translate("MainWindow", "Turkey"))
        self.radio_azerbaijan.setText(_translate("MainWindow", "Azerbaijan"))
        self.radio_greece.setText(_translate("MainWindow", "Greece"))
        self.group_box_education.setTitle(_translate("MainWindow", "Education"))
        self.radio_university.setText(_translate("MainWindow", "University"))
        self.radio_elementary.setText(_translate("MainWindow", "Elementary School"))
        self.radio_high_school.setText(_translate("MainWindow", "High School"))
        self.radio_masters.setText(_translate("MainWindow", "Master's Degree"))
